# Generated by Django 5.2.4 on 2025-07-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
