# Generated by Django 5.2.4 on 2025-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="suggestion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
