# Generated by Django 5.2.4 on 2025-07-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0003_annotation_suggestion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotation",
            old_name="suggestion",
            new_name="suggestions",
        ),
    ]
