# Generated by Django 5.2.4 on 2025-07-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0004_rename_suggestion_annotation_suggestions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotation",
            name="suggestions",
        ),
        migrations.CreateModel(
            name="Suggestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="annotation.annotation",
                    ),
                ),
            ],
        ),
    ]
