# Generated by Django 5.2.4 on 2025-07-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0005_remove_annotation_suggestions_suggestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="suggestions_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="suggestions",
            name="annotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions_set",
                to="annotation.annotation",
            ),
        ),
    ]
